version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ecommerce_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root_password
      - SPRING_REDIS_HOST=redis
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=root_password
    entrypoint: ["/app/wait-for-mysql.sh", "java", "-jar", "app.jar"]

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=ecommerce_db
      - MYSQL_ROOT_PASSWORD=root_password

  redis:
    image: redis:latest
    ports:
      - "6379:6379" 