version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ecommerce_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root_password
      - SPRING_REDIS_HOST=redis
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=root_password
      - STRIPE_SECRET_KEY=***REMOVED***51RNRK22UPUsh6WXCmaWOSfckwxWpGNErfigvHxY0kObq0dYmBiUyCyjeQiLmfnK0Jo35GZSTvKynUAPEagXGeCnL00Wajs412m
      - STRIPE_PUBLISHABLE_KEY=pk_test_51RNRK22UPUsh6WXC6tYxBTm6KJyFiJ35vX26EVjq8xU87FeyVbmOxVmibwaPpKM2A9DI56TjbxfNCwjRtyVGBYKA00Nt44E8pM
      - STRIPE_WEBHOOK_SECRET=***REMOVED***51RNRK22UPUsh6WXCmaWOSfckwxWpGNErfigvHxY0kObq0dYmBiUyCyjeQiLmfnK0Jo35GZSTvKynUAPEagXGeCnL00Wajs412m
      - GOOGLE_CLIENT_ID=***REMOVED***vsru3nn9gauhs1iuvcjkncvasc1t5l0o.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=***REMOVED***BqYTbads8vKuSel6ij-l1N_7R-_i
    entrypoint: ["/app/wait-for-mysql.sh", "java", "-jar", "app.jar"]

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=ecommerce_db
      - MYSQL_ROOT_PASSWORD=root_password

  redis:
    image: redis:latest
    ports:
      - "6379:6379" 